name: Generate Snake

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ChanudiMallikaArachchi
          outputs: output/snake.svg

      - name: Push
        run: |
          git add output/snake.svg
          git -c user.name="github-actions[bot]" -c user.email="github-actions[bot]@users.noreply.github.com" commit -m "Update snake" || true
          git push
